# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

# Redirect port for udacity simulator
udaPort = 4567

# Basic provisioning script
$script = <<SCRIPT
echo Provisioning system ...
SCRIPT

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "ubuntu/xenial64"
  config.vm.provision "shell", inline: $script
  config.vm.network "forwarded_port", host: udaPort, guest: udaPort, protocol: "tcp", auto_correct: true
end
